version: "3.7"
services:
 open_alpr:
  image: nilssn8000213/open_alpr_python3:beta
  restart: unless-stopped
  environment:
   - API_HOST=127.0.0.1
   - API_PORT=9090
  working_dir: /tmp/
  ports: 
   - "80:80"

  command: bash -c "pip3 install -r requirements.txt && uvicorn main:app --port 80"
  #tail -f /dev/null pip3 install -r requirements.txt && uvicorn main:app --reload

  volumes:
    - C:/Personal/server:/tmp/
  privileged: true
