version: "3.7"
services:
 open_alpr:
  image: nilssn8000213/open_alpr_python3:beta
  restart: unless-stopped
  working_dir: /tmp/
  ports: 
   - "4300:8000"

  command: bash -c "pip3 install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
  #tail -f /dev/null 
  volumes:
    - C:/Personal/server:/tmp/
  privileged: true
